### ISSUE TITLE
"Disk write speed is too low, write queue is filling up" when recording IMU data on Femto Mega, SDK 1.8.1

### ISSUE THREAD

**Issue by gregorijk** [orbbec/OrbbecSDK-K4A-Wrapper#14]
- OS with Version: Windows 11 22H2
 - SDK Version:  1.8.1 (x64)
 - Firmware version:  Depth camera 1.1.5

When running 'k4arecorder.exe' with Femto Mega camera and including the IMU data (--imu ON), I get the following errors "Disk write speed is too low, write queue is filling up." Log attached. When recording without IMU data (--imu OFF), the recording seems to work fine. Similar behavior is also observed when using k4a::record from the SDK wrapper in custom code.

When running the original Azure Kinect k4arecorder no such issues are observed on the same computer.

[
[OrbbecSDK.log.txt](https://github.com/orbbec/OrbbecSDK-K4A-Wrapper/files/13272432/OrbbecSDK.log.txt)
](url)

**Comment by zhonghong322** [comment]
Thank you for the feedback, we will fix this issue in the new firmware version.

**Comment by zhonghong322** [comment]
Please download the firmware, upgrade tool, and upgrade documentation, and then follow the upgrade documentation to perform firmware upgrades.
https://github.com/orbbec/OrbbecFirmware/releases/tag/Femto-Mega-Firmware

**Comment by hzcyf** [comment]
Close, it is fixed and no more feedback.
