### ISSUE TITLE
Accelerometer readings are negative

### ISSUE THREAD

**Issue by jbrownkramer** [orbbec/OrbbecSDK-K4A-Wrapper#17]
**Describe the bug**
The coordinate axes of the accelerometer are all negative what the Azure Kinect Returns.  The expected behavior of the accelerometer is specified in the Azure Kinect DK documentation.  https://learn.microsoft.com/en-us/azure/kinect-dk/coordinate-systems

**To Reproduce**
- Read the accelerometer data from an Azure Kinect and a Femto Bolt in the same orientation.
![image](https://github.com/orbbec/OrbbecSDK-K4A-Wrapper/assets/4051645/afc97227-02d2-4b70-b75c-10826060902a)

**Expected behavior**
The accelerometer output should have the same orientation as the Azure Kinect.

**Comment by zhonghong322** [comment]
Thank you for reporting the issue, we will fix it in the upcoming versions

**Comment by hzcyf** [comment]
This issue has been resolved in this [commit](https://github.com/orbbec/OrbbecSDK-K4A-Wrapper/commit/719945cbaf35671a46c017805df17f389b7adb9d). It is advisable to synchronize your code directly from the main branch.
