### ISSUE TITLE
k4a_image_set_system_timestamp_nsec does not work

### ISSUE THREAD

**Issue by bibigone** [orbbec/OrbbecSDK-K4A-Wrapper#31]
k4a_image_set_system_timestamp_nsec function does not work as expected. It changes device timestamp, but system. I suppose, it is because of misprint in the following line: https://github.com/orbbec/OrbbecSDK-K4A-Wrapper/blob/0ca9c101e7b5efa67c79c88316be49b4c01ed1e8/src/orbbec/ob_k4a_impl.cpp#L1433

**Comment by zhonghong322** [comment]
Thank you for the feedback. We will fix it，However, currently, the interface for setting the system timestamp only provides accuracy up to milliseconds.

**Comment by hzcyf** [comment]
This problem has been fixed in this [commit](https://github.com/orbbec/OrbbecSDK-K4A-Wrapper/commit/139aed38fe9873ee84bba35dee5ff836ecee571e). You can sync the code directly from the main branch.
