### ISSUE TITLE
OrbbecSDK-K4A-Wrapper C# Version

### ISSUE THREAD

**Issue by frenchtouchXR** [orbbec/OrbbecSDK-K4A-Wrapper#4]
Hello, 

Are you planning to release a C# or Unity version of the K4A wrapper ?

**Comment by hzcyf** [comment]
The C# version are packaged directly based on the K4A API, but we haven't tested and released them yet. We will do so as soon as possible. You can attempt to compile and test with the source code in this repository.

**Comment by frenchtouchXR** [comment]
I managed to build something with C# and I have the color and depth playing on Unity. But everytime I try to use the Transformation functions from K4a Unity crashed. 
transformation.DepthImageToColorCamera
transformation.DepthImageToPointCloud
transformation.ColorImageToDepthCamera
It crashes for the 3 transformations without exception. 

Unity crashlog : 

ArgumentNullException: Value cannot be null.
Parameter name: depth
  at Microsoft.Azure.Kinect.Sensor.Transformation.DepthImageToColorCamera (Microsoft.Azure.Kinect.Sensor.Image depth) [0x00049] in C:\Users\franc\OrbbecSDK-K4A-Wrapper\src\csharp\SDK\Transformation.cs:71 
  at test.Update () [0x00027] in C:\Users\franc\Documents\TestK4aWrapperCsharp\Assets\test.cs:109 

(Filename: C:/Users/franc/OrbbecSDK-K4A-Wrapper/src/csharp/SDK/Transformation.cs Line: 71)

ArgumentNullException: Value cannot be null.
Parameter name: depth
  at Microsoft.Azure.Kinect.Sensor.Transformation.DepthImageToColorCamera (Microsoft.Azure.Kinect.Sensor.Image depth) [0x00049] in C:\Users\franc\OrbbecSDK-K4A-Wrapper\src\csharp\SDK\Transformation.cs:71 
  at test.Update () [0x00027] in C:\Users\franc\Documents\TestK4aWrapperCsharp\Assets\test.cs:109 

(Filename: C:/Users/franc/OrbbecSDK-K4A-Wrapper/src/csharp/SDK/Transformation.cs Line: 71)

[I20231009 15:16:03.349638 20000 FrameBufferManager.cpp:33] New frame buffer allocated=0.703559MB, total usage: {allocated=33.7567MB, max limit=2048MB}
[I20231009 15:16:03.350638 29276 FrameBufferManager.cpp:33] New frame buffer allocated=0.703551MB, total usage: {allocated=34.4602MB, max limit=2048MB}
[I20231009 15:16:03.378201 16800 FrameBufferManager.cpp:33] New frame buffer allocated=0.703559MB, total usage: {allocated=35.1638MB, max limit=2048MB}
[I20231009 15:16:03.379201 20000 FrameBufferManager.cpp:33] New frame buffer allocated=0.703551MB, total usage: {allocated=35.8673MB, max limit=2048MB}
[I20231009 15:16:03.407565 16800 FrameBufferManager.cpp:33] New frame buffer allocated=0.703559MB, total usage: {allocated=36.5709MB, max limit=2048MB}
[I20231009 15:16:03.408565 29276 FrameBufferManager.cpp:33] New frame buffer allocated=0.703551MB, total usage: {allocated=37.2744MB, max limit=2048MB}
[I20231009 15:16:03.444559 18056 FrameBufferManager.cpp:33] New frame buffer allocated=0.703559MB, total usage: {allocated=37.978MB, max limit=2048MB}
[I20231009 15:16:03.445559 38008 FrameBufferManager.cpp:33] New frame buffer allocated=0.703551MB, total usage: {allocated=38.6816MB, max limit=2048MB}
[I20231009 15:16:03.483594 36256 FrameBufferManager.cpp:33] New frame buffer allocated=0.703559MB, total usage: {allocated=39.3851MB, max limit=2048MB}
[I20231009 15:16:03.484594 18056 FrameBufferManager.cpp:33] New frame buffer allocated=0.703551MB, total usage: {allocated=40.0887MB, max limit=2048MB}
[I20231009 15:16:03.578207 11032 FrameBufferManager.hpp:58] FrameBufferManager created! @class libobsensor::FrameBufferManager<class libobsensor::DepthFrame>, obj addr:1625376946608, frame obj total size:0.000433922MB
[I20231009 15:16:03.578207 11032 FrameBufferManager.cpp:107] DepthFrame bufferManager created!
[I20231009 15:16:03.578207 11032 FrameBufferManager.cpp:33] New frame buffer allocated=0.000433922MB, total usage: {allocated=40.0891MB, max limit=2048MB}
Crash!!!
SymInit: Symbol-SearchPath: 'C:/Program Files/Unity/Hub/Editor/2021.3.21f1/Editor/Data/Mono;.;C:\Users\franc\Documents\TestK4aWrapperCsharp;C:\Users\franc\Documents\TestK4aWrapperCsharp\Library\BurstCache\JIT;C:\Program Files\Unity\Hub\Editor\2021.3.21f1\Editor;C:\Windows;C:\Windows\system32;', symOptions: 534, UserName: 'franc'
OS-Version: 10.0.0
C:\Program Files\Unity\Hub\Editor\2021.3.21f1\Editor\Unity.exe:Unity.exe (00007FF68C6F0000), size: 74289152 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2021.3.21.5473
C:\Windows\SYSTEM32\ntdll.dll:ntdll.dll (00007FF86AC10000), size: 2179072 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2215
C:\Windows\System32\KERNEL32.DLL:KERNEL32.DLL (00007FF869AC0000), size: 802816 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2215
C:\Windows\System32\KERNELBASE.dll:KERNELBASE.dll (00007FF867FC0000), size: 3817472 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2215
C:\Windows\System32\CRYPT32.dll:CRYPT32.dll (00007FF868410000), size: 1466368 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2215
C:\Windows\System32\ucrtbase.dll:ucrtbase.dll (00007FF868580000), size: 1118208 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.608
C:\Windows\System32\USER32.dll:USER32.dll (00007FF86A7F0000), size: 1761280 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2215
C:\Windows\System32\win32u.dll:win32u.dll (00007FF8687D0000), size: 155648 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2283
C:\Windows\System32\GDI32.dll:GDI32.dll (00007FF868C10000), size: 167936 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2215
C:\Windows\System32\gdi32full.dll:gdi32full.dll (00007FF868800000), size: 1146880 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2215
C:\Windows\System32\msvcp_win.dll:msvcp_win.dll (00007FF868370000), size: 630784 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.608
C:\Windows\System32\ADVAPI32.dll:ADVAPI32.dll (00007FF86AA60000), size: 720896 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2215
C:\Windows\System32\msvcrt.dll:msvcrt.dll (00007FF869C30000), size: 684032 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 7.0.22621.608
C:\Windows\System32\sechost.dll:sechost.dll (00007FF86A9A0000), size: 679936 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2215
C:\Program Files\Unity\Hub\Editor\2021.3.21f1\Editor\optix.6.0.0.dll:optix.6.0.0.dll (00007FF844E80000), size: 208896 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 6.0.0.0
C:\Program Files\Unity\Hub\Editor\2021.3.21f1\Editor\s3tcompress.dll:s3tcompress.dll (00007FF843700000), size: 180224 (result: 0), SymType: '-deferred-', PDB: ''
A crash has been intercepted by the crash handler. For call stack and other details, see the latest crash report generated in:
 * C:/Users/franc/AppData/Local/Temp/Unity/Editor/Crashes
