### ISSUE TITLE
Turning the LED on and off works in reverse

### ISSUE THREAD

**Issue by Rudizzzz** [orbbec/OrbbecSDK-K4A-Wrapper#42]
**Describe the bug**

The _Microsoft.Azure.Kinect.Sensor.DeviceConfiguration.DisableStreamingIndicator_ works in reverse.
If I set this parameter = true, the led turns on.
If I set this parameter = false, the led turns off.

**To Reproduce**

1. Initialize a DeviceConfiguration object where DisableStreamingIndicator = true.
2. Start the camera
3. Check the led status
4. Stop the camera
5. Initialize a DeviceConfiguration object where DisableStreamingIndicator = false.
6. Start the camera
7. Check the led status

**Expected behavior**

Since the name of the parameter is DisableStreamingIndicator, not EnableStreamingIndicator, the led should turn off if the parameter = true and turn on if the parameter = false.
The Kinect 4 Azure SDK works fine, so this fix is important to preserve backward compatibility.

**Logs**

**Screenshots**

**Desktop (please complete the following information):**
 - OS with Version:  Windows 10
 - SDK Version:   1.9.1 (OrbbecSDK.dll = 1.9.4)
 - Firmware version:   1.0.9

**Additional context**

**Comment by ChuckM90** [comment]
Maybe it could have been solved here #43

**Comment by Rudizzzz** [comment]
Yes,
I'll wait for the official release then.
Thanks

**Comment by zhonghong322** [comment]
The code has been modified and committed to the develop branch（https://github.com/orbbec/OrbbecSDK-K4A-Wrapper/commits/develop/）. Going forward, new features will be added, and they will be released together in a future version.

**Comment by zhonghong322** [comment]
The k4a wrapper 1.9.2 has been fixed and release.
